detection_method: std_dagmm
dagmm_hyperparameters_path: ./dagmm/std_dagmm/dagmm_hyperparameters.yaml
dagmm_ignore_up_to: 0
dagmm_model_path: ./dagmm/std_dagmm/dagmm_model_mnist.pt
dagmm_output_dir: '-----'
dagmm_threshold_path: ./dagmm/std_dagmm/dagmm_anomaly_threshold.yaml
do_data_collection: false
gmm_parameters_paths:
  cov: ./dagmm/std_dagmm/gmm_param_cov.pt
  mean: ./dagmm/std_dagmm/gmm_param_mean.pt
  mixture: ./dagmm/std_dagmm/gmm_param_mixture.pt
