detection_method: delta_dagmm
dagmm_hyperparameters_path: ./dagmm/delta_dagmm/models/mnist/100/dagmm_hyperparameters.yaml
dagmm_ignore_up_to: 1
dagmm_model_path: ./dagmm/delta_dagmm/models/mnist/100/model.pt
dagmm_output_dir: ./dagmm/delta_dagmm/dagmm_train_data/mnist/100/run_malicious_2
dagmm_threshold_path: ./dagmm/delta_dagmm/models/mnist/100/dagmm_anomaly_threshold.yaml
do_data_collection: false
do_test_data_collection: false
gmm_parameters_paths:
  cov: ./dagmm/delta_dagmm/models/mnist/100/gmm_param_cov.pt
  mean: ./dagmm/delta_dagmm/models/mnist/100/gmm_param_mean.pt
  mixture: ./dagmm/delta_dagmm/models/mnist/100/gmm_param_mixture.pt
